"""initial_schema_v1

Revision ID: fc17a53ea5e7
Revises: 
Create Date: 2026-09-06 22:36:36.986032

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc17a53ea5e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('rtsp_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('target_fps', sa.Integer(), nullable=False),
    sa.Column('reconnect_delay', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_cameras_status'), ['status'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=False),
    sa.Column('model_file', sa.String(length=255), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_module_name'), ['module_name'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settings_key'), ['key'], unique=True)

    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_severity'), ['severity'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('enrollment_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_number'), ['employee_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_employees_status'), ['status'], unique=False)

    op.create_table('expression_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('expression_label', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expression_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expression_events_department_id'), ['department_id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_track_id'), ['track_id'], unique=False)

    op.create_table('users_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_admins_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_admins_username'), ['username'], unique=True)

    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('polygon_json', sa.Text(), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zones_camera_id'), ['camera_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_attendance_date')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_employee_id'), ['employee_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)

    op.create_table('face_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('vector_512d', sa.LargeBinary(), nullable=False),
    sa.Column('view_type', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_templates_employee_id'), ['employee_id'], unique=False)

    op.create_table('identity_verifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.Column('match_margin', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_verifications_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_identity_verifications_track_id'), ['track_id'], unique=False)

    op.create_table('manual_review_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('candidate_data_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_review_items_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_review_items_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_review_items_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_review_items_status'), ['status'], unique=False)

    op.create_table('presence_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('presence_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presence_sessions_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_sessions_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_sessions_track_id'), ['track_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presence_sessions_zone_id'), ['zone_id'], unique=False)

    op.create_table('unknown_people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unknown_people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unknown_people_resolution_status'), ['resolution_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_unknown_people_track_id'), ['track_id'], unique=False)

    op.create_table('visitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('host_employee_id', sa.Integer(), nullable=True),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitors_badge_number'), ['badge_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_visitors_host_employee_id'), ['host_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitors_status'), ['status'], unique=False)

    op.create_table('activity_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('activity_state', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['presence_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_segments_session_id'), ['session_id'], unique=False)

    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=False),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users_admins.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['attendance_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_corrections_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_corrections_record_id'), ['record_id'], unique=False)

    op.create_table('unknown_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unknown_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['unknown_id'], ['unknown_people.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unknown_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unknown_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unknown_events_unknown_id'), ['unknown_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unknown_events_zone_id'), ['zone_id'], unique=False)

    op.create_table('visitor_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visitor_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visitor_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_events_visitor_id'), ['visitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visitor_events_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitor_events_zone_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_events_visitor_id'))
        batch_op.drop_index(batch_op.f('ix_visitor_events_camera_id'))

    op.drop_table('visitor_events')
    with op.batch_alter_table('unknown_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unknown_events_zone_id'))
        batch_op.drop_index(batch_op.f('ix_unknown_events_unknown_id'))
        batch_op.drop_index(batch_op.f('ix_unknown_events_camera_id'))

    op.drop_table('unknown_events')
    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_record_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_admin_user_id'))

    op.drop_table('attendance_corrections')
    with op.batch_alter_table('activity_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_segments_session_id'))

    op.drop_table('activity_segments')
    with op.batch_alter_table('visitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visitors_status'))
        batch_op.drop_index(batch_op.f('ix_visitors_host_employee_id'))
        batch_op.drop_index(batch_op.f('ix_visitors_badge_number'))

    op.drop_table('visitors')
    with op.batch_alter_table('unknown_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unknown_people_track_id'))
        batch_op.drop_index(batch_op.f('ix_unknown_people_resolution_status'))

    op.drop_table('unknown_people')
    with op.batch_alter_table('presence_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presence_sessions_zone_id'))
        batch_op.drop_index(batch_op.f('ix_presence_sessions_track_id'))
        batch_op.drop_index(batch_op.f('ix_presence_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_presence_sessions_employee_id'))
        batch_op.drop_index(batch_op.f('ix_presence_sessions_camera_id'))

    op.drop_table('presence_sessions')
    with op.batch_alter_table('manual_review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_review_items_status'))
        batch_op.drop_index(batch_op.f('ix_manual_review_items_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_manual_review_items_item_type'))
        batch_op.drop_index(batch_op.f('ix_manual_review_items_camera_id'))

    op.drop_table('manual_review_items')
    with op.batch_alter_table('identity_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_verifications_track_id'))
        batch_op.drop_index(batch_op.f('ix_identity_verifications_employee_id'))

    op.drop_table('identity_verifications')
    with op.batch_alter_table('face_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_templates_employee_id'))

    op.drop_table('face_templates')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_date'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zones_camera_id'))

    op.drop_table('zones')
    with op.batch_alter_table('users_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_admins_username'))
        batch_op.drop_index(batch_op.f('ix_users_admins_role_id'))

    op.drop_table('users_admins')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_track_id'))
        batch_op.drop_index(batch_op.f('ix_tracks_camera_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('expression_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expression_events_department_id'))

    op.drop_table('expression_events')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_status'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_number'))
        batch_op.drop_index(batch_op.f('ix_employees_department_id'))

    op.drop_table('employees')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_severity'))
        batch_op.drop_index(batch_op.f('ix_system_events_event_type'))

    op.drop_table('system_events')
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settings_key'))

    op.drop_table('settings')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_module_name'))

    op.drop_table('model_versions')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_status'))
        batch_op.drop_index(batch_op.f('ix_cameras_name'))

    op.drop_table('cameras')
    # ### end Alembic commands ###
